### PR TITLE
metadata DB support for inputs - build DB, query, etc.

### PR DESCRIPTION
**Pull request by davidraila**

### CODE REVIEW

**Comment by davidraila** [comment]
Also includes compressed test data and last updated actual nearline data

**Comment by LandonTClipp** [comment]
Waiting to merge until Yizhao's code has been merged with master.

**Comment by LandonTClipp** [comment]
@kyang2014 

As per your request in your email to me, please look this over and merge when you are ready. This should not interfere with anything, it is just the database script.

**Comment by kyang2014** [comment]
Merge the database script

**Pull request merged**
